server:
  port: 8080
  servlet:
    context-path: /pt1


spring:
  application:
    name: seata-payment-transfer1
  main:
    allow-bean-definition-overriding: true


  ######################## DB CONFIGURATION #####################
  datasource:
    druid-datasource:
      url: jdbc:mysql://localhost:3306/cloudpayment?serverTimezone=UTC #useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: rootroot
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000


